name: Setup
inputs:
  node-version:
    type: string
    require: false
    default: 16.x
  install-deps:
    type: boolean
    require: false
    default: true
runs:
  using: composite
  steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{iputs.node-version}} 
      uses: actions/setup-node@v3
      with:
        node-version: ${{inputs.node-version}}
        cache: 'yarn'
    - uses: prisma/action-node-cache-dependencies@main
      if: inputs.install-deps
